# Generated by Django 4.2 on 2023-04-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillhub', '0002_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='place',
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillhub.year'),
        ),
    ]
