# Generated by Django 4.2 on 2023-04-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillhub', '0005_alter_person_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillhub.department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(choices=[('Information technology', 'Information technology')], max_length=150),
        ),
    ]
